In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import pylab as plt

%matplotlib inline

In [52]:
spain = pd.read_csv("data/all_tables_Spain_cleaned.csv",index_col=0)
parties = set(list(spain.columns))

del spain["Unnamed: 0.1"]
spain = spain.dropna(thresh=len(spain)/5,axis=1)

In [53]:
spain.head()

,BNG,CiU,ERC,IU,Lead,PNV,PP,PSOE,Podemos,Turnout,UPyD,date,firm,size,Party_poll,Newspaper_poll,Polling_firm,Number_polling_firms
1,0.0,5.218,NaN,9.018,16.8,1.35,0.0,64.8276,0.0,68,NaN,1989-10-29,PSOE,NaN,True,NaN,PSOE,1
2,0.0,NaN,NaN,0.000,NaN,NaN,0.0,0.0000,0.0,NaN,NaN,1989-10-29,Metis/RTVE,40000.0,False,RTVE,Metis,1
3,0.0,NaN,NaN,0.000,NaN,NaN,0.0,0.0000,0.0,NaN,NaN,1989-10-29,Opina,NaN,False,NaN,Opina,1
4,0.0,NaN,NaN,0.000,NaN,NaN,0.0,40.1176,0.0,NaN,NaN,1989-10-29,Demoscopia/Cadena SER,91451.0,False,Cadena SER,Demoscopia,1
5,0.0,NaN,NaN,0.000,NaN,NaN,0.0,0.0000,0.0,NaN,NaN,1989-10-29,Sigma Dos/COPE,NaN,False,COPE,Sigma Dos,1

In [45]:
spain.groupby("firm").count()["date"].sort_values()

firm
Interior Ministry                    1
Metis/RTVE                           1
Llorente & Cuenca                    1
Line-Staff                           1
JJD/lainformacion.com                1
Ipsos–Eco/RTVE                       1
Ipsos–Eco/Prensa Ibérica             1
Ipsos/RTVE                           1
Ipsos/Faro de Vigo                   1
Metra Seis                           1
Iope–Etmar/Tele 5                    1
Inner Line                           1
Imagen & Opinión/ABC                 1
Ikerfel/Vocento                      1
ISIS                                 1
INE                                  1
Gallup/El Periódico                  1
Gallup/Cambio 16                     1
GIPEyOP/Mediaflows                   1
Intercampo/CIS                       1
Metroscopia                          1
Motivación/COPE                      1
Municipal Elections                  1
UCD                                  1
Tábula V/La Gaceta                   1
Tábula V                             1
Typol                                1
Tribuna                              1
Telemarket                           1
TNS Demoscopia/Vocento               1
                                  ...
Ipsos/Expansión                     13
DYM/ABC                             13
Metra Seis/Colpisa                  14
GESOP/El Periòdic                   17
GAD/COPE                            18
La Vanguardia                       19
Intercampo/GETS                     19
MyWord/Cadena SER                   20
Opina/El País                       21
Encuestamos                         23
Noxa/La Vanguardia                  24
Demoscopia/El País                  26
Vox Pública/El Periódico            28
GAD3/ABC                            30
Opina/La Vanguardia                 32
JM&A/Público                        34
GESOP/El Periódico                  40
Obradoiro de Socioloxía/Público     41
Celeste-Tel                         48
Celeste-Tel/eldiario.es             52
ASEP                                60
Simple Lógica                       63
TNS Demoscopia/Antena 3             63
Metroscopia/El País                 80
Gallup                              81
NC Report/La Razón                  89
Invymark/laSexta                   116
CIS                                116
Sigma Dos/El Mundo                 138
Opina/Cadena SER                   167
Name: date, Length: 175, dtype: int64